using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace StatsUI.StatsXML
{
    //------------------------------------------------------------------------------
    // <auto-generated>
    //     This code was generated by a tool.
    //     Runtime Version:4.0.30319.42000
    //
    //     Changes to this file may cause incorrect behavior and will be lost if
    //     the code is regenerated.
    // </auto-generated>
    //------------------------------------------------------------------------------

    using System.Xml.Serialization;

    // 
    // This source code was auto-generated by xsd, Version=4.8.3928.0.
    // 


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class Speletajs
    {

        private string lomaField;

        private string uzvardsField;

        private string vardsField;

        private string nrField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Loma
        {
            get
            {
                return this.lomaField;
            }
            set
            {
                this.lomaField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Uzvards
        {
            get
            {
                return this.uzvardsField;
            }
            set
            {
                this.uzvardsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Vards
        {
            get
            {
                return this.vardsField;
            }
            set
            {
                this.vardsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Nr
        {
            get
            {
                return this.nrField;
            }
            set
            {
                this.nrField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class Spele
    {

        private SpeleKomanda[] komandaField;

        private SpeleT[] tField;

        private SpeleVT[] vtField;

        private string laiksField;

        private string skatitajiField;

        private string vietaField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Komanda", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SpeleKomanda[] Komanda
        {
            get
            {
                return this.komandaField;
            }
            set
            {
                this.komandaField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("T", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SpeleT[] T
        {
            get
            {
                return this.tField;
            }
            set
            {
                this.tField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("VT", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SpeleVT[] VT
        {
            get
            {
                return this.vtField;
            }
            set
            {
                this.vtField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Laiks
        {
            get
            {
                return this.laiksField;
            }
            set
            {
                this.laiksField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Skatitaji
        {
            get
            {
                return this.skatitajiField;
            }
            set
            {
                this.skatitajiField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Vieta
        {
            get
            {
                return this.vietaField;
            }
            set
            {
                this.vietaField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class SpeleKomanda
    {

        private Speletajs[] speletajiField;

        private SpeleKomandaMainasMaina[] mainasField;

        private Speletajs[] pamatsastavsField;

        private SpeleKomandaSodiSods[] sodiField;

        private SpeleKomandaVartiVG[] vartiField;

        private string nosaukumsField;

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Speletajs", typeof(Speletajs), IsNullable = false)]
        public Speletajs[] Speletaji
        {
            get
            {
                return this.speletajiField;
            }
            set
            {
                this.speletajiField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Maina", typeof(SpeleKomandaMainasMaina), Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
        public SpeleKomandaMainasMaina[] Mainas
        {
            get
            {
                return this.mainasField;
            }
            set
            {
                this.mainasField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Speletajs", typeof(Speletajs), IsNullable = false)]
        public Speletajs[] Pamatsastavs
        {
            get
            {
                return this.pamatsastavsField;
            }
            set
            {
                this.pamatsastavsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Sods", typeof(SpeleKomandaSodiSods), Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
        public SpeleKomandaSodiSods[] Sodi
        {
            get
            {
                return this.sodiField;
            }
            set
            {
                this.sodiField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("VG", typeof(SpeleKomandaVartiVG), Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
        public SpeleKomandaVartiVG[] Varti
        {
            get
            {
                return this.vartiField;
            }
            set
            {
                this.vartiField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Nosaukums
        {
            get
            {
                return this.nosaukumsField;
            }
            set
            {
                this.nosaukumsField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class SpeleKomandaMainasMaina
    {

        private string laiksField;

        private string nr1Field;

        private string nr2Field;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Laiks
        {
            get
            {
                return this.laiksField;
            }
            set
            {
                this.laiksField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Nr1
        {
            get
            {
                return this.nr1Field;
            }
            set
            {
                this.nr1Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Nr2
        {
            get
            {
                return this.nr2Field;
            }
            set
            {
                this.nr2Field = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class SpeleKomandaSodiSods
    {

        private string laiksField;

        private string nrField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Laiks
        {
            get
            {
                return this.laiksField;
            }
            set
            {
                this.laiksField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Nr
        {
            get
            {
                return this.nrField;
            }
            set
            {
                this.nrField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class SpeleKomandaVartiVG
    {

        private SpeleKomandaVartiVGP[] pField;

        private string laiksField;

        private string nrField;

        private string sitiensField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("P", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SpeleKomandaVartiVGP[] P
        {
            get
            {
                return this.pField;
            }
            set
            {
                this.pField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Laiks
        {
            get
            {
                return this.laiksField;
            }
            set
            {
                this.laiksField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Nr
        {
            get
            {
                return this.nrField;
            }
            set
            {
                this.nrField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Sitiens
        {
            get
            {
                return this.sitiensField;
            }
            set
            {
                this.sitiensField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class SpeleKomandaVartiVGP
    {

        private string nrField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Nr
        {
            get
            {
                return this.nrField;
            }
            set
            {
                this.nrField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class SpeleT
    {

        private string uzvardsField;

        private string vardsField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Uzvards
        {
            get
            {
                return this.uzvardsField;
            }
            set
            {
                this.uzvardsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Vards
        {
            get
            {
                return this.vardsField;
            }
            set
            {
                this.vardsField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class SpeleVT
    {

        private string uzvardsField;

        private string vardsField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Uzvards
        {
            get
            {
                return this.uzvardsField;
            }
            set
            {
                this.uzvardsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Vards
        {
            get
            {
                return this.vardsField;
            }
            set
            {
                this.vardsField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class NewDataSet
    {

        private object[] itemsField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Spele", typeof(Spele))]
        [System.Xml.Serialization.XmlElementAttribute("Speletajs", typeof(Speletajs))]
        public object[] Items
        {
            get
            {
                return this.itemsField;
            }
            set
            {
                this.itemsField = value;
            }
        }
    }

}
