//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StatsUI.StatsDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class game
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public game()
        {
            this.goals = new HashSet<goal>();
            this.passes = new HashSet<pass>();
            this.penalties = new HashSet<penalty>();
            this.players_games = new HashSet<players_games>();
        }
    
        public long id { get; set; }
        public string place { get; set; }
        public System.DateTime date { get; set; }
        public long team1 { get; set; }
        public long team2 { get; set; }
        public Nullable<long> points_team1 { get; set; }
        public Nullable<long> points_team2 { get; set; }
        public Nullable<long> referee_main { get; set; }
        public Nullable<long> referee_assist1 { get; set; }
        public Nullable<long> referee_assis2 { get; set; }
        public Nullable<long> spectators { get; set; }
    
        public virtual referee referee { get; set; }
        public virtual referee referee1 { get; set; }
        public virtual referee referee2 { get; set; }
        public virtual team team { get; set; }
        public virtual team team3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<goal> goals { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pass> passes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<penalty> penalties { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<players_games> players_games { get; set; }
    }
}
